### ISSUE TITLE
US1 gallery

### ISSUE THREAD

**Issue by KevinBlbd** [KevinBlbd/capstone-project#3]
## Value proposition

As a user
I want to see different street art pictures
in order to get inspiration

## Description

<img width="367" alt="wireframe3" src="https://user-images.githubusercontent.com/125892809/233298708-b4f61099-1bf0-4f9b-873d-ee985756d363.png">

## Acceptance criteria

- [ ] All art pieces are displayed as a list
- [ ] Each art piece's image is displayed 

## Tasks

- [ ] create an array of sample pictures
- [ ] create an image component that displays a single picture
- [ ] create the component to render a list of image components

Size: M

**Comment by F-Kirchhoff** [comment]
Hey Kevin,
this is looking great, please give your tasks a bit more detail and I guess your app should not be named capstone App but something else, so you might want to change the title in your wireframe.

**Comment by BenRodProd** [comment]
LGTM
