### ISSUE TITLE
US2 Form

### ISSUE THREAD

**Issue by KevinBlbd** [KevinBlbd/capstone-project#4]
## Value proposition

As a user
I want to upload a picture from my files
in order to see it displayed on the app

## Description

<img width="298" alt="wf13" src="https://user-images.githubusercontent.com/125892809/233595103-ed7ac099-d986-49e5-be1d-e0bdf68affbc.png">

<img width="298" alt="wf12" src="https://user-images.githubusercontent.com/125892809/233591965-d79401e8-9e17-4a90-afb1-d328e435d17f.png">

<img width="298" alt="wf14" src="https://user-images.githubusercontent.com/125892809/233595155-fe347b0f-c5cb-43a7-8185-e4e70bc1f12a.png">

## Acceptance criteria

- [ ] button "+" on homepage
- [ ] form is displayed as a pop-up on button "+" click
- [ ] form have entries (add file, location, artist name, type)
- [ ] form contain required fields : image URL, location, type
- [ ] form is being submit when required fields are filled and "OK" button is clicked
- [ ] when form submitted the pop-up disappear and the uploaded picture appear in the gallery

## Tasks

- [ ] create a button "+" on homepage
- [ ] create form pop-up component with 4 fields : image URL (required), location (required), artist (optional), type (required)
- [ ] create a state for pop-up
- [ ] create and implement the new Object from the submit in the Gallery-Array
- [ ] create a route "/gallery/pieces/add" with index.js

Size: M

**Comment by CJAkkuec** [comment]
>  link form page to display when button is clicked

I think I know what you mean, but the wording is a little confusing here. 🤔 
By the way, for the image upload you may want to look at [this](https://cloudinary.com/ip/gr-sea-gg-brand-home-base?utm_source=google&utm_medium=search&utm_campaign=goog_selfserve_brand_wk22_replicate_core_branded_keyword&utm_term=1329&campaignid=17601148700&adgroupid=141182782954&keyword=cloudinary&device=c&matchtype=e&adposition=&gad=1&gclid=CjwKCAjw6IiiBhAOEiwALNqncW1bBOQw940kLUSXbfa9walFSo_vjz_9oKFScMTo9AatjDJBjEnY6RoCT_sQAvD_BwE). 👀
