### ISSUE TITLE
US 3 - Picture Detail page

### ISSUE THREAD

**Issue by KevinBlbd** [KevinBlbd/capstone-project#5]
## Value proposition

As a user
I want to click on a picture
in order to see the picture's details

<img width="670" alt="wf17" src="https://user-images.githubusercontent.com/125892809/233637183-d1f3eaf3-5e55-4562-a0f7-919ec47ca9ef.png">

## Acceptance criteria

- [ ] clicking a picture in the gallery open the picture detail page
- [ ] the picture details shown are: the picture in a larger version, the name of the artist, the location and the type of picture (tag choice)
- [ ] on the detail page a "back" button is placed on top of the picture' details
- [ ] the back button is bringing the user back to the homepage

## Tasks

- [ ] create the detail page template
- [ ] create artistName display component
- [ ] create location display component
- [ ] create tag display component
- [ ] create dummy data: artistName, location, type
- [ ] create "back" button bringing back to homepage

Size: M
